# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3a099949aca1277acfab30bd068381d1f9814498964f46e16999dc5e56fafcab57eee3f8f4834a86cdf2114c124a065afa26218123b1cbcb0eb1ee052cc04733

test:
  secret_key_base: cd6de360db622f787b93b427751a1679e5573fb19579120c19dd9df63d947071fa5b11e740d4a48e0957eba4c5bf703a63213f059b93474fd7ba84b3dc76baef

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
